
version: "3.7"
services: 
           
    mariadb:
        container_name: db
        image:  mariadb:10.4
        ports: 
            - "${DB_PORT}:3306"
        restart: unless-stopped
        volumes: 
            - ./.data/mysql:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            #- MYSQL_USER=devs
            #- MYSQL_PASSWORD='devs12345'
            MYSQL_DATABASE: ${DB_DATABASE}

        networks: 
            - lamp_network
        

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        depends_on: 
            - mariadb
            - app
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
        networks: 
            - lamp_network
        ports: 
            - "${PHPMYADMIN_PORT}:80" 
            
    app:
        container_name: app
        depends_on: 
            - mariadb
        #restart: unless-stopped
        
        volumes: 
            - ./public/:/var/www/html/:cached

        networks: 
            - lamp_network
        ports: 
            - "${APP_PORT}:80"
          #  - 8082:8080
        build: 
            context: ./.docker/
            dockerfile: Dockerfile
        #command: bash -c "chown -R apache:apache /var/www/html" 
         #   bash -c "chown -R apache:apache /var/www/html" 
        


    
    
networks:
    lamp_network:
       driver: bridge
                            
            
     
    
         
    
        

   
            
